### ISSUE TITLE
Credit card length

### ISSUE THREAD

**Issue by Gongreg** [observing/creditcard#7]
Hello,
You should totally check card number length too. Since checking if card is valid without it is kinda strange. I can get 6 digit card numbers easily.

**Comment by 3rd-Eden** [comment]
Well, if the length isn't correct, the validation would fail.

**Comment by Gongreg** [comment]
I have tried to use code '4462 03' and creditcard.parse said that it is a valid code and crecitCardType was visa.

**Comment by 3rd-Eden** [comment]
Well that is obvious a validator bug then. As saying that is valid code is obviously wrong, but guessing the correct credit card is intentional as it visa has a certain card range.
