### ISSUE TITLE
Include Mastercard "Series 2" BINs

### ISSUE THREAD

**Issue by beastbytes** [observing/creditcard#9]
Mastercard are to issue cards later this year with new Bank Identification Numbers starting with 2 (hence series 2). Details [here](https://www.mctestcards.com/help)

The regex used for card type identification needs updating to include them.

**Comment by 3rd-Eden** [comment]
Thanks for bringing that to our attention!

**Comment by 3rd-Eden** [comment]
It appears to be a range of `(222100-272099)` so wouldn't be that hard to update the regexp.
